# Funding configuration for GitHub Sponsors and other platforms

github: [mansour2024]
patreon: # Add Patreon username if applicable
open_collective: # Add Open Collective username if applicable
ko_fi: # Add Ko-fi username if applicable
tidelift: # Add Tidelift platform-name/package-name if applicable
community_bridge: # Add Community Bridge project-name if applicable
liberapay: # Add Liberapay username if applicable
issuehunt: # Add IssueHunt username if applicable
otechie: # Add Otechie username if applicable
lfx_crowdfunding: # Add LFX Crowdfunding project-name if applicable
custom: # Add up to 4 custom sponsorship URLs
