//! PERF-01 Section 4: deterministic avian-genetics fastpath.
//!
//! The generic Kernel_03 biomedical path memory-maps `bio_medical_module.tcz`
//! and scores the whole corpus for every request. On the reference hardware a
//! full LLM generation takes minutes, so canonical bird-breeding probability
//! questions deserve a cheaper, exact path.
//!
//! This module answers ONLY canonical single-locus crosses (autosomal
//! recessive, autosomal dominant, sex-linked recessive in ZZ/ZW birds) from a
//! manifest compiled by `tools/compile_bio_medical_module.py --fastpath` and
//! **embedded at Rust compile time** — zero disk I/O, zero LLM tokens, zero
//! randomness. Composite phenotypes (Rainbow, Blackwing, Hagoromo) are
//! recognized but explicitly decline a single-locus answer; ambiguous or
//! unrecognized queries fall back to the full mmap'ed corpus, so the fastpath
//! can only ever be a strict improvement over the previous path.

use serde::{Deserialize, Serialize};

use crate::error::{Result, VortexAtomsError};

/// Stable identity of the embedded fastpath manifest.
pub const FASTPATH_SCHEMA: &str = "vortex_atoms_ai_avian_fastpath";
/// Current manifest revision (bump together with the compile tool).
pub const FASTPATH_VERSION: u32 = 1;
/// Kernel_03 logic-module id selected by Kernel_02 for avian genetics math.
pub const FASTPATH_MODULE_ID: &str = "bio.avian.fastpath";
/// Prefix that identifies fastpath-produced summaries (used for telemetry).
pub const FASTPATH_SUMMARY_MARKER: &str = "fastpath.avian.genetics:";

/// Manifest is compiled into the binary, so it must always be present.
const EMBEDDED_MANIFEST: &str = include_str!("../../knowledge/avian_genetics_fastpath.json");

/// Compiled avian-genetics fastpath loaded from the embedded manifest.
#[derive(Clone, Debug)]
pub struct AvianGeneticsFastpath {
    manifest: AvianFastpathManifest,
}

/// Top-level compiled manifest structure.
#[derive(Clone, Debug, Serialize, Deserialize, Eq, PartialEq)]
pub struct AvianFastpathManifest {
    pub schema: String,
    pub version: u32,
    pub generated_by: String,
    pub keywords_avian: Vec<String>,
    pub keywords_probability: Vec<String>,
    pub mutations: Vec<FastpathMutation>,
    pub templates: FastpathTemplates,
}

/// A known avian mutation (single-locus or explicitly composite).
#[derive(Clone, Debug, Serialize, Deserialize, Eq, PartialEq)]
pub struct FastpathMutation {
    pub key: String,
    pub name: String,
    #[serde(default)]
    pub species: Vec<String>,
    pub mode: String,
    pub note: String,
}

/// Canonical single-locus outcome tables grouped by inheritance mode.
#[derive(Clone, Debug, Serialize, Deserialize, Eq, PartialEq)]
pub struct FastpathTemplates {
    pub autosomal_recessive: Vec<OutcomeTemplate>,
    pub autosomal_dominant: Vec<OutcomeTemplate>,
    pub sex_linked_recessive: Vec<OutcomeTemplate>,
}

/// One canonical cross template: left/right parent phenotypes map to a
/// deterministic outcome.
#[derive(Clone, Debug, Serialize, Deserialize, Eq, PartialEq)]
pub struct OutcomeTemplate {
    pub id: String,
    pub left: String,
    pub right: String,
    pub outcome: String,
}

/// Deterministic answer produced by the fastpath.
#[derive(Clone, Debug, Serialize, Deserialize, Eq, PartialEq)]
pub struct FastpathAnswer {
    /// `true` when the query resolved to a canonical template or a documented
    /// composite-phenotype note; `false` means "use the corpus instead".
    pub recognized: bool,
    /// Matched template id, e.g. `ar_split_x_split`.
    pub template_id: Option<String>,
    /// Inheritance mode, e.g. `sex_linked_recessive`.
    pub mode: Option<String>,
    /// Species tags from the matched mutation (empty for generic templates).
    pub species: Vec<String>,
    /// Resolved offspring expectation.
    pub outcome: Option<String>,
    /// Explainer note (mutation note or ambiguity guidance).
    pub note: Option<String>,
    /// Provenance / performance banner.
    pub banner: String,
    /// Veterinary safety boundary notice.
    pub safety_notice: String,
}

impl AvianGeneticsFastpath {
    /// Load the fastpath from the manifest embedded at compile time.
    ///
    /// # Panics
    /// Panics if the embedded manifest is missing or malformed. The manifest
    /// is generated by `tools/compile_bio_medical_module.py --fastpath` before
    /// every build, so this is a build invariant rather than a runtime error.
    pub fn embedded() -> Self {
        Self::from_json(EMBEDDED_MANIFEST)
            .expect("embedded avian-genetics fastpath manifest is valid")
    }

    /// Parse and validate a fastpath manifest from JSON text.
    pub fn from_json(json: &str) -> Result<Self> {
        let manifest: AvianFastpathManifest = serde_json::from_str(json).map_err(|error| {
            VortexAtomsError::InvalidKnowledgeExtension(format!(
                "avian-genetics fastpath manifest is not valid JSON: {error}"
            ))
        })?;
        if manifest.schema != FASTPATH_SCHEMA {
            return Err(VortexAtomsError::InvalidKnowledgeExtension(format!(
                "avian-genetics fastpath manifest has unknown schema '{}' (expected '{FASTPATH_SCHEMA}')",
                manifest.schema
            )));
        }
        if manifest.version != FASTPATH_VERSION {
            return Err(VortexAtomsError::InvalidKnowledgeExtension(format!(
                "avian-genetics fastpath manifest has unsupported version {} (expected {FASTPATH_VERSION})",
                manifest.version
            )));
        }
        Ok(Self { manifest })
    }

    /// The parsed manifest (useful for provenance checks).
    pub fn manifest(&self) -> &AvianFastpathManifest {
        &self.manifest
    }

    /// Deterministically resolve a prompt against the canonical tables.
    ///
    /// The whole function is allocation-light and free of any I/O, randomness,
    /// or time dependence, so identical prompts always produce identical
    /// answers.
    pub fn answer(&self, prompt: &str) -> FastpathAnswer {
        let lower = prompt.to_ascii_lowercase();
        let avian = self
            .manifest
            .keywords_avian
            .iter()
            .any(|keyword| lower.contains(keyword));
        if !avian {
            return self.not_recognized("no avian-genetics intent detected");
        }

        let probability_or_cross = self
            .manifest
            .keywords_probability
            .iter()
            .any(|keyword| lower.contains(keyword))
            || mentions_cross(&lower);
        if !probability_or_cross {
            return self.not_recognized("avian intent without a probability/cross query");
        }

        if let Some(mutation) = self.detect_mutation(&lower) {
            if mutation.mode == "composite_phenotype" {
                return FastpathAnswer {
                    recognized: true,
                    template_id: None,
                    mode: Some("composite_phenotype".to_string()),
                    species: mutation.species.clone(),
                    outcome: None,
                    note: Some(mutation.note.clone()),
                    banner: self.banner(),
                    safety_notice: safety_notice().to_string(),
                };
            }
            if let Some(parents) = parse_parents(&lower) {
                if let Some(template) =
                    self.match_cross(mutation.mode.as_str(), parents.0, parents.1)
                {
                    let outcome = template.outcome.clone();
                    return FastpathAnswer {
                        recognized: true,
                        template_id: Some(template.id.clone()),
                        mode: Some(mutation.mode.clone()),
                        species: mutation.species.clone(),
                        outcome: Some(outcome),
                        note: Some(self.species_note(mutation)),
                        banner: self.banner(),
                        safety_notice: safety_notice().to_string(),
                    };
                }
            }
        }

        let mode = self.detect_mode(&lower);
        let parents = match parse_parents(&lower) {
            Some(parents) => parents,
            None => {
                return self.not_recognized("no canonical cross pattern detected");
            }
        };
        let template = match self.match_cross(mode.as_str(), parents.0, parents.1) {
            Some(template) => template,
            None => {
                return self.not_recognized(
                    "cross did not match a canonical single-locus template",
                );
            }
        };

        FastpathAnswer {
            recognized: true,
            template_id: Some(template.id.clone()),
            mode: Some(mode.clone()),
            species: Vec::new(),
            outcome: Some(template.outcome.clone()),
            note: Some(format!("Canonical {mode} template used for this cross.")),
            banner: self.banner(),
            safety_notice: safety_notice().to_string(),
        }
    }

    fn banner(&self) -> String {
        format!(
            "compiled avian-genetics manifest {} v{} (embedded; no disk I/O; no LLM)",
            self.manifest.schema, self.manifest.version
        )
    }

    fn not_recognized(&self, reason: &str) -> FastpathAnswer {
        FastpathAnswer {
            recognized: false,
            template_id: None,
            mode: None,
            species: Vec::new(),
            outcome: None,
            note: Some(format!("Not a canonical fastpath query: {reason}")),
            banner: self.banner(),
            safety_notice: safety_notice().to_string(),
        }
    }

    fn detect_mutation(&self, lower: &str) -> Option<&FastpathMutation> {
        self.manifest
            .mutations
            .iter()
            .find(|mutation| lower.contains(&mutation.key))
    }

    fn species_note(&self, mutation: &FastpathMutation) -> String {
        if mutation.species.is_empty() {
            mutation.note.clone()
        } else {
            format!(
                "{} ({})",
                mutation.note,
                mutation.species.join(", ")
            )
        }
    }

    fn detect_mode(&self, lower: &str) -> String {
        let sex_linked_hint = [
            "sex-linked",
            "sex linked",
            "zz",
            "zw",
            "sexlinked",
            "male",
            "female",
        ]
        .iter()
        .any(|needle| lower.contains(needle));
        if sex_linked_hint {
            return "sex_linked_recessive".to_string();
        }
        if lower.contains("dominant") {
            return "autosomal_dominant".to_string();
        }
        "autosomal_recessive".to_string()
    }

    fn match_cross(&self, mode: &str, left: ParentPhenotype, right: ParentPhenotype) -> Option<OutcomeTemplate> {
        let templates: &[OutcomeTemplate] = match mode {
            "autosomal_dominant" => &self.manifest.templates.autosomal_dominant,
            "sex_linked_recessive" => &self.manifest.templates.sex_linked_recessive,
            _ => &self.manifest.templates.autosomal_recessive,
        };

        let left_key = left.canonical_key();
        let right_key = right.canonical_key();
        if left_key.is_empty() || right_key.is_empty() {
            return None;
        }

        templates
            .iter()
            .find(|template| {
                (template.left == left_key && template.right == right_key)
                    || (template.left == right_key && template.right == left_key)
            })
            .cloned()
    }
}

/// One parent-phrase phenotype extracted from a cross expression.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ParentPhenotype {
    Visual,
    Split,
    Normal,
    SingleFactor,
    DoubleFactor,
    VisualMale,
    SplitMale,
    NormalMale,
    VisualFemale,
    NormalFemale,
    Unknown,
}

impl ParentPhenotype {
    /// Stable key used to match rows in the canonical tables.
    pub fn canonical_key(self) -> &'static str {
        match self {
            Self::Visual => "visual",
            Self::Split => "split",
            Self::Normal => "normal",
            Self::SingleFactor => "single_factor",
            Self::DoubleFactor => "double_factor",
            Self::VisualMale => "visual_male",
            Self::SplitMale => "split_male",
            Self::NormalMale => "normal_male",
            Self::VisualFemale => "visual_female",
            Self::NormalFemale => "normal_female",
            Self::Unknown => "",
        }
    }
}

/// Split a prompt around its cross separator (e.g. `x`, `x `, `crossed with`).
pub fn parse_parents(lower: &str) -> Option<(ParentPhenotype, ParentPhenotype)> {
    let (left_text, right_text) = split_cross(lower)?;
    let left = classify_parent(left_text);
    let right = classify_parent(right_text);
    if left == ParentPhenotype::Unknown || right == ParentPhenotype::Unknown {
        return None;
    }
    Some((left, right))
}

fn split_cross(lower: &str) -> Option<(&str, &str)> {
    // Also handle verb-first expressions: "cross a split budgie with a visual
    // budgie", "breed a opaline male with a normal female budgie" start the
    // cross at position 0 with no surrounding whitespace, so the bounded
    // 'x'-family markers below never fire. Split on the " with a "/" with an "
    // boundary first in that case.
    if lower.starts_with("cross a ")
        || lower.starts_with("cross an ")
        || lower.starts_with("cross the ")
    {
        for marker in [" with a ", " with an ", " with the "] {
            if let Some(position) = lower.find(marker) {
                let left = &lower[7..position].trim();
                let right = &lower[position + marker.len()..];
                let right = right.split(['?', '!', '.', ';', '\n']).next().unwrap_or("").trim();
                if !left.is_empty() && !right.is_empty() {
                    return Some((left, right));
                }
            }
        }
        return None;
    }
    // Prefer unambiguous separators before the bare 'x' fallback, because 'x'
    // also appears inside words such as "exact" or "sex-linked".
    for marker in [" x ", "×", " crossed with ", " cross ", " bred with ", " paired with ", "x"] {
        if let Some(position) = lower.find(marker) {
            let right_start = position + marker.len();
            let left = &lower[..position].trim();
            let right = &lower[right_start..];
            // Cut trailing sentence content after a bounded window so the second
            // parent phrase does not absorb unrelated words.
            let mut right = right.split(|character: char| {
                character == '?' || character == '!' || character == '.'
                    || character == ';' || character == '\n'
            });
            let right = right.next().unwrap_or("").trim();
            if !left.is_empty() && !right.is_empty() {
                return Some((left, right));
            }
        }
    }
    None
}

fn classify_parent(text: &str) -> ParentPhenotype {
    let text = text.trim();
    if text.contains("double") {
        ParentPhenotype::DoubleFactor
    } else if text.contains("single") {
        ParentPhenotype::SingleFactor
    } else if text.contains("visual") {
        if text.contains("male") {
            ParentPhenotype::VisualMale
        } else if text.contains("female") {
            ParentPhenotype::VisualFemale
        } else {
            ParentPhenotype::Visual
        }
    } else if text.contains("split") || text.contains("carrier") {
        if text.contains("female") {
            // Females cannot be split for Z-linked recessives; do not guess.
            ParentPhenotype::Unknown
        } else if text.contains("male") {
            ParentPhenotype::SplitMale
        } else {
            ParentPhenotype::Split
        }
    } else if text.contains("normal") {
        if text.contains("male") {
            ParentPhenotype::NormalMale
        } else if text.contains("female") {
            ParentPhenotype::NormalFemale
        } else {
            ParentPhenotype::Normal
        }
    } else {
        ParentPhenotype::Unknown
    }
}

fn mentions_cross(lower: &str) -> bool {
    lower.contains('×')
        || lower.contains(" x ")
        || lower.contains(" crossed with ")
        || lower.contains(" cross ")
        || lower.contains(" bred with ")
        || lower.contains(" paired with ")
        // Verb-first canonical forms ("cross a split budgie with a visual
        // budgie", "breed a opaline male with a normal female budgie") start
        // the expression with the cross verb rather than an infix separator,
        // so gate on the bound word form explicitly.
        || lower.starts_with("cross ")
        || lower.starts_with("crossing ")
        || lower.starts_with("breed ")
        || lower.starts_with("breeding ")
        || lower.contains(" to cross ")
        || lower.contains(" cross a ")
        || lower.contains(" cross an ")
        || lower.contains(" cross the ")
        || lower.contains(" cross two ")
        || lower.contains(" breed a ")
        || lower.contains(" breed an ")
        || lower.contains(" breed two ")
}

/// Kernel_03 entry: answer canonically or fall back to the corpus.
pub fn run_avian_genetics_fastpath(prompt: &str) -> Result<String> {
    let fastpath = AvianGeneticsFastpath::embedded();
    let answer = fastpath.answer(prompt);
    if answer.recognized {
        Ok(answer.to_kernel_summary())
    } else {
        // Graceful degradation: the full mmap'ed biomedical corpus still
        // answers (with the same safety boundary) for non-canonical queries.
        crate::bio_medical_module::run_bio_medical_module(prompt)
    }
}

fn safety_notice() -> &'static str {
    "Safety boundary: veterinary and avian-genetics content is educational breeding, \
     triage, and husbandry support only. Sick or injured animals require a qualified \
     veterinarian."
}

impl FastpathAnswer {
    /// Format the answer for the Kernel_03 event stream and state store.
    ///
    /// The first line always starts with [`FASTPATH_SUMMARY_MARKER`] so the
    /// kernel can bump fastpath telemetry without re-running the matcher.
    pub fn to_kernel_summary(&self) -> String {
        let header = match (&self.template_id, &self.mode) {
            (Some(template), Some(mode)) => format!(
                "{FASTPATH_SUMMARY_MARKER} template '{}' mode '{}'",
                template, mode
            ),
            (None, Some(mode)) => {
                format!("{FASTPATH_SUMMARY_MARKER} composite mode '{}'", mode)
            }
            _ => FASTPATH_SUMMARY_MARKER.to_string(),
        };

        let mut output = format!("{header}; {}\n{}", self.banner, self.safety_notice);
        if let Some(outcome) = &self.outcome {
            output.push_str("\n\nExpected offspring: ");
            output.push_str(outcome);
            output.push('.');
        }
        if let Some(note) = &self.note {
            output.push_str("\n\n");
            output.push_str(note);
        }
        output
    }
}